title: Open Internet Manifest
description: A living manifesto for a free, open and decentralized internet
# Base URL â€“ leeg lokaal, correct op GitHub Pages
baseurl: "/Open_Internet_Manifest"  # Voor GitHub Pages
url: "https://openinternetmanifest.github.io"  


defaults:
  - scope:
      path: "nl"
    values:
      lang: "NL"
  - scope:
      path: "en"
    values:
      lang: "EN"

exclude:
 
  - venv
  - tools

# Forceer rebuild
rebuild_trigger: v2025-12-30-final