title: Open Internet Manifest
description: A living manifesto for a free, open and decentralized internet
# Base URL – leeg lokaal, correct op GitHub Pages
baseurl: "{{ site.baseurl_override | default: '' }}"
url: ""

# Voor GitHub Pages – automatisch /Open_Internet_Manifest
# Geen extra config nodig – GitHub zet het zelf


defaults:
  - scope:
      path: "nl"
    values:
      lang: "NL"
  - scope:
      path: "en"
    values:
      lang: "EN"

exclude:
  - Gemfile
  - Gemfile.lock
  - venv
  - tools

# Forceer rebuild
rebuild_trigger: v2025-12-30-final