title: Open Internet Manifest
description: A living manifesto for a free, open and decentralized internet
baseurl: "/Open_Internet_Manifest"  # Dit houdt links intact
defaults:
  - scope:
      path: "nl"
    values:
      lang: "NL"
  - scope:
      path: "en"
    values:
      lang: "EN"